
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "URL_ВАШЕГО_НОВОГО_ПРОЕКТА"; // Замените на URL нового проекта
const SUPABASE_PUBLISHABLE_KEY = "КЛЮЧ_ВАШЕГО_НОВОГО_ПРОЕКТА"; // Замените на ключ нового проекта

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
